stages:
  - build
  - deploy

variables:
  PROJECT_ID: "proven-sum-435500-p1"          # Replace with your Google Cloud Project ID
  CLUSTER_NAME: "flask-cluster"               # Replace with your GKE cluster name
  GKE_ZONE: "us-central1-a"                   # Replace with your GKE cluster zone
  IMAGE_NAME: "backend"
  KUBE_NAMESPACE: "default"                   # Kubernetes namespace for deployment

# Step 1: Build the Docker image
build:
  stage: build
  image: gcr.io/cloud-builders/docker
  script:
    - docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_SHA
  only:
    - main

# Step 2: Deploy to GKE
deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    # Authenticate with GCP
    - echo $GOOGLE_APPLICATION_CREDENTIALS_JSON
    - echo $GOOGLE_APPLICATION_CREDENTIALS_JSON | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone $GKE_ZONE
    
    # Update the Kubernetes deployment with the new image
    - kubectl set image deployment/flask-app-deployment flask-app=gcr.io/$PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_SHA --namespace=$KUBE_NAMESPACE
  only:
    - main
