apiVersion: v1
kind: Namespace
metadata:
  name: flask-backend-ns
---

apiVersion: v1
kind: Secret
metadata:
  name: flask-backend-secrets
  namespace: flask-backend-ns
type: Opaque
data:
  DB_PASSWORD: dGVzdDEyMw==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-backend-configmap
  namespace: flask-backend-ns
data:
  DB_HOST: "34.46.69.185"
  DB_NAME: "test-db"
  DB_USER: "admin1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
  namespace: flask-backend-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend-app
  template:
    metadata:
      labels:
        app: flask-backend-app
    spec:
      containers:
        - name: flask-backend-app
          image: gcr.io/proven-sum-435500-p1/flask-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-backend-configmap
            - secretRef:
                name: flask-backend-secrets
          env:
           - name: GOOGLE_APPLICATION_CREDENTIALS
             value: "./key.json"    
      imagePullSecrets:
        - name: gcr-json-key

---

apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  namespace: flask-backend-ns
spec:
  type: LoadBalancer
  selector:
    app: flask-backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000